### ISSUE TITLE
jsx uncomment not work

### ISSUE THREAD

**Issue by luckmonkey** [borela/naomi#23]
jsx uncomment not work

**Comment by borela** [comment]
I sent some commits on the master branch to fix the issue for single line comments. Unfortunately for multi line comments I still have no solution.

**Comment by faiwer** [comment]
![img_16_01_11 38 31_be6ef9f6e8f](https://user-images.githubusercontent.com/744114/34973453-cf9a51f4-fab1-11e7-996f-a99a46d73262.png)
In-tag comments isn't highlighted (as comments) too :)

**Comment by borela** [comment]
I'll have to use python scripts to fix the comment toggle. I'll give it a shot this week.

**Comment by borela** [comment]
@faiwer 
Is that valid syntax? Normally on JSX you would have to do something like: `{/* comment */}`

**Comment by faiwer** [comment]
@borela, I don't know exactly, but it works in babel :) Aslo eslint shows the `parsing error: unexpected token` in the next code:
```js
<Tag {/* comment */}/>
```
How do you can comment line in an attribute jsx section another way?

**Comment by borela** [comment]
[Babel is indeed parsing comments directly, love it!](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=FA4HgEwSwN2ACeB6J8CGGHoLwCICMuWSAVOhvCUsAHxhLQw1A&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact%2Cstage-0&prettier=false&targets=&version=6.26.0)

I released a patch https://github.com/borela/naomi/releases/tag/v3.1.0 that will highlight `//` and `//*` near attributes.

**Comment by faiwer** [comment]
Thank you!

**Comment by Ding-Fan** [comment]
JSX toggle comment still can't work
<img width="327" alt="image" src="https://user-images.githubusercontent.com/26438549/36850392-9d21e80a-1da1-11e8-8574-fdbc20b92fe6.png">
<img width="320" alt="image" src="https://user-images.githubusercontent.com/26438549/36850423-b7e80e62-1da1-11e8-94c8-f12abcae1a69.png">

**Comment by borela** [comment]
@Ding-Fan I am researching the sublime api to fix this one through a plugin.

**Comment by borela** [comment]
I created a plugin https://github.com/borela/naomi/pull/92 that should be able to toggle JS/JSX comments, the code is here https://github.com/borela/naomi/blob/feature/comment-toggle-plugin/plugin/ToggleJsxComment.py

I would love feedback before merging and realeasing it, can you guys take a look at it? I did some tests locally and tried to fine tune it to get the UX right (it turns out, coding such feature is not intuitive at all).

**Comment by borela** [comment]
I created a plugin https://github.com/borela/naomi/pull/92 that should be able to toggle JS/JSX comments, the code is here https://github.com/borela/naomi/blob/feature/comment-toggle-plugin/plugin/ToggleJsxComment.py

I would love feedback before merging and realeasing it, can you guys take a look at it? I did some tests locally and tried to fine tune it to get the UX right (it turns out, coding such feature is not intuitive at all).

@luckmonkey @faiwer @Ding-Fan

**Comment by Ding-Fan** [comment]
I don't know how to use the single .py file with sublime3 so I removed Naomi through "Package Control: Remove Package", followed [Manual Installation](https://github.com/borela/naomi/tree/feature/comment-toggle-plugin#manual-installation) installed it, restarted Sublime3.

Nothing changed.

**Comment by borela** [comment]
@Ding-Fan 
You need to clone the repository or download the package through github https://github.com/borela/naomi/archive/feature/comment-toggle-plugin.zip at the directory:

   * **OS X:** ~/Library/Application Support/Sublime Text 3/Packages/User
   * **Linux:** ~/.config/sublime-text-3/Packages/User
   * **Windows:** %APPDATA%\Sublime Text 3\Packages/User

**Comment by borela** [comment]
I am doing some final tweaks, it looks like I got most edge cases, almost ready to release it.

**Comment by borela** [comment]
I did some tests and it looks like it is detecting correctly when to add the braces even for block comments, released it: https://github.com/borela/naomi/releases/tag/v3.8.0  package control should pick the update in about ~2h.

Feel free to reopen this issue or open new ones if it causes regression.

**Comment by franciscolourenco** [comment]
Not working at all for me 🤔

![naomi-jsx-comments](https://user-images.githubusercontent.com/208149/37203000-8c856b84-238c-11e8-9019-6f3f1365486a.gif)

Naomi 3.10.1

**Comment by borela** [comment]
@franciscolourenco I'll take a look at it at the office.

**Comment by borela** [comment]
@franciscolourenco Please check if the console (View > Show Console) shows an error when you try to comment, I am not able to reproduce it on my machine.

**Comment by franciscolourenco** [comment]
@borela no errors. I'm using Sublime 3133, what about you?

**Comment by borela** [comment]
3157 I'll try with an older version.

**Comment by franciscolourenco** [comment]
Just tried with 3143 but got the same results

**Comment by borela** [comment]
Found the issue, I forgot to override the shortcut for macs, the line https://github.com/borela/naomi/blob/master/Default.sublime-keymap#L229 only works for Linux and Windows while the default package uses:

```
	{ "keys": ["super+forward_slash"], "command": "toggle_comment", "args": { "block": false } },
	{ "keys": ["super+alt+forward_slash"], "command": "toggle_comment", "args": { "block": true } },
```

for mac.

I'll publish the patch in a minute.

**Comment by borela** [comment]
@franciscolourenco https://github.com/borela/naomi/compare/v3.10.1...v3.10.2 published the patch, as the shortcut for OSX was not replaced, in your case, it was using sublime's default behavior.

**Comment by boycce** [comment]
In Sublime 4 you can't uncomment a rxjs line when your cursor position is at the end, it simply recomments that line
![image](https://user-images.githubusercontent.com/2629988/186288371-16ba18cc-ca7a-4f78-8ebf-a1ce96dccd69.png)
